---
- name: Install source dependencies for RTPProxy
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ rtpproxy_source_dependencies }}"

- name: Create RTPProxy Install directory
  file:
    path: "{{ rtpproxy_install_dir }}"
    state: directory
    owner: "{{ rtpproxy_user }}"
    group: "{{ rtpproxy_group }}"
    mode: 0755

- name: Identifying the latest software release
  uri:
    url: "{{ rtpproxy_latest_release_url }}"
    return_content: yes
  register: latest_release
  when: rtpproxy_version == "latest"

- set_fact:
    rtpproxy_download_version={{ latest_release.json.tag_name | trim('v') }}
  when: rtpproxy_version == "latest"

- set_fact:
    rtpproxy_download_version={{ rtpproxy_version }}
  when: rtpproxy_version != "latest"

- name: Clone RTPProxy GitHub repository
  git:
    repo: https://github.com/sippy/rtpproxy.git
    dest: "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version}}"
    version: "v{{ rtpproxy_download_version }}"
    recursive: true
    clone: true

- name: Run RTPProxy configure
  shell: umask 0022 && ./configure --prefix={{ rtpproxy_install_dir }}
  args:
    chdir: "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version }}"
    creates: "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version }}/Makefile"

- name: Compile RTPProxy
  shell: umask 0022 && make -j{{ ansible_processor_cores | default(1) + 1 }}
  args:
    chdir: "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version }}"
    creates: "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version}}/src/rtpproxy"

- name: Install RTPProxy
  shell: umask 0022 && make install
  args:
    chdir: "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version }}"
    creates: "{{ rtpproxy_install_dir }}/bin/rtpproxy"
  notify: restart rtpproxy

- name: Register RTPProxy binaries
  command: ls -1 {{ rtpproxy_install_dir }}/bin
  register: _rtpproxy_binaries
  changed_when: false

- name: Add RTPProxy binaries to alternatives
  alternatives:
    name: "{{ item }}"
    path: "{{ rtpproxy_install_dir }}/bin/{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items: "{{ _rtpproxy_binaries.stdout_lines }}"

# Cleanup Source Files
- name: Clean up the source files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version }}"
    - "{{ rtpproxy_download_dir }}/rtpproxy-{{ rtpproxy_download_version }}.tar.gz"
  when: rtpproxy_cleanup_downloads|bool
  become: true
