---
- name: Set OS Specific variables
  include_tasks: preflight.yml

- name: Check if RTPProxy is installed
  command: "which {{ rtpproxy_install_dir }}/bin/rtpproxy"
  register: rtpproxy_exists
  failed_when: false
  ignore_errors: true
  changed_when: false

- include_tasks: install_from_source.yml    # noqa name[missing]
  when: rtpproxy_force_install|bool or rtpproxy_exists.rc != 0

- include_tasks: configure.yml    # noqa name[missing]
