---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        rtpproxy_version: "{{ lookup('env', 'RTPPROXY_VERSION') }}"

    - name: Install prerequisites
      block:
        - name: Update apt cache
          when: ansible_os_family == "Debian"
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false

        - package:
            name: "{{ item }}"
            state: present
          with_items: 
            - rsyslog

  roles:
    - role: ansible-role-rtpproxy
      tags:
        - rtpproxy
